# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

brutes <- function(probabilities, length, thresholds) {
    .Call(`_clobe_brutes`, probabilities, length, thresholds)
}

gdistance <- function(human, model, universal, weight, frequencies, normalize = TRUE, xtdo = FALSE) {
    .Call(`_clobe_gdistance`, human, model, universal, weight, frequencies, normalize, xtdo)
}

imac <- function(probabilities, thresholds) {
    .Call(`_clobe_imac`, probabilities, thresholds)
}

